rate: 10 

target:
  input_type: 2
  topic_pose: "cmd_vel_vm_integrated"
  topic_twist: "cmd_vel"

current:
  input_type: 0
  topic_pose: "robot_pose_stamped"
  topic_odom: "odom_enc"

lyapunov: [3.4,10.0,2.5]
topic_output: "/cmd_vel"
reference: [0.0 ,0.5, 0.0]